import React from "react";
import ToggleComponent from "./1-useToggle/ToggleComponent";
import FetchComponent from "./10-useFetch/FetchComponent";
import ScriptComponent from "./11-useScript/ScriptComponent";
import DeepCompareEffectComponent from "./12-useDeepCompareEffect/DeepCompareEffectComponent";
import EventListenerComponent from "./13-useEventListener/EventListenerComponent";
import OnScreenComponent from "./14-useOnScreen/OnScreenComponent";
import WindowSizeComponent from "./15-useWindowSize/WindowSizeComponent";
import MediaQueryComponent from "./16-useMediaQuery/MediaQueryComponent";
import GeolocationComponent from "./17-useGeolocation/GeolocationComponent";
import SizeComponent from "./19-useSize/SizeComponent";
import TimeoutComponent from "./2-useTimeout/TimeoutComponent";
import EffectOnceComponent from "./20-useEffectOnce/EffectOnceComponent";
import ClickOutsideComponent from "./21-useClickOutside/ClickOutsideComponent";
import DarkModeComponent from "./22-useDarkMode/DarkModeComponent";
import CopyToClipboardComponent from "./23-useCopyToClipboard/CopyToClipboardComponent";
import CookieComponent from "./24-useCookie/CookieComponent";
import TranslationComponent from "./25-useTranslation/TranslationComponent";
import OnlineStatusComponent from "./26-useOnlineStatus/OnlineStatusComponent";
import RenderCountComponent from "./27-useRenderCount/RenderCountComponent";
import DebugInformationComponent from "./28-useDebugInformation/DebugInformationComponent";
import HoverComponent from "./29-useHover/HoverComponent";
import DebounceComponent from "./3-useDebounce/DebounceComponent";
import LongPressComponent from "./30-useLongPress/LongPressComponent";
import UpdateEffectComponent from "./4-useUpdateEffect/UpdateEffectComponent";
import ArrayComponent from "./5-useArray/ArrayComponent";
import StateWithHistoryComponent from "./7-useStateWithHistory/StateWithHistory";
import StorageComponent from "./8-useStorage/StorageComponent";
import AsyncComponent from "./9-useAsync/AsyncComponent";

function App() {
  // return <ToggleComponent />;
  // return <TimeoutComponent />;
  // return <DebounceComponent />;
  // return <UpdateEffectComponent />;
  // return <ArrayComponent />;
  // return <PreviousComponent />;
  // return <StateWithHistoryComponent />;
  // return <StorageComponent />;
  // return <AsyncComponent />;
  // return <FetchComponent />;
  // return <ScriptComponent />;
  // return <DeepCompareEffectComponent />;
  // return <EventListenerComponent />;
  // return <OnScreenComponent />;
  // return <WindowSizeComponent />;
  // return <MediaQueryComponent />;
  // return <GeolocationComponent />
  // return <StateWithHistoryComponent />;
  // return <SizeComponent />;
  // return <EffectOnceComponent />;
  // return <ClickOutsideComponent />;
  // return <DarkModeComponent />;
  // return <CopyToClipboardComponent />;
  // return <CookieComponent />;
  // return <TranslationComponent />;
  // return <OnlineStatusComponent />;
  // return <RenderCountComponent />;
  // return <DebugInformationComponent />;
  // return <HoverComponent />;
  return <LongPressComponent />;
}

export default App;
